apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
- namespace.yaml
- ../../base
- ../../base/location
- ../../base/kafka-connect
- patches/kafka-connect-connector.yaml
- istio/mtls.yaml
- istio/retry.yaml
- istio/authorization.yaml
labels:
- includeSelectors: true
  pairs:
    environment: staging
patches:
- path: patches/virtualservice-hosts.yaml
  target:
    kind: VirtualService
    name: yas-ingress-vs
- path: patches/auth.yaml
- path: patches/rolling-update-one-node.yaml
  target:
    kind: Deployment
- path: patches/storefront-ui.yaml
  target:
    kind: Deployment
    name: storefront-ui
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
  target:
    kind: Deployment
    name: .*
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 0
  target:
    kind: Deployment
    name: swagger-ui
images:
- name: bingsu1103/backoffice
  newTag: v1.0.3
- name: bingsu1103/backoffice-bff
  newTag: v1.0.3
- name: bingsu1103/cart
  newTag: v1.0.3
- name: bingsu1103/customer
  newTag: v1.0.3
- name: bingsu1103/inventory
  newTag: v1.0.3
- name: bingsu1103/location
  newTag: v1.0.3
- name: bingsu1103/media
  newTag: v1.0.3
- name: bingsu1103/order
  newTag: v1.0.3
- name: bingsu1103/payment
  newTag: v1.0.3
- name: bingsu1103/product
  newTag: v1.0.3
- name: bingsu1103/sampledata
  newTag: v1.0.3
- name: bingsu1103/search
  newTag: v1.0.3
- name: bingsu1103/storefront
  newTag: v1.0.3
- name: bingsu1103/storefront-bff
  newTag: v1.0.3
- name: bingsu1103/tax
  newTag: v1.0.3
