apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
  - ../../base
labels:
  - pairs:
      environment: staging
    includeSelectors: true
patches:
  - target:
      kind: Deployment
      name: ".*"
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
images:
  - name: bingsu1103/media
    newTag: latest
  - name: bingsu1103/product
    newTag: latest
  - name: bingsu1103/order
    newTag: latest
  - name: bingsu1103/inventory
    newTag: latest
  - name: bingsu1103/payment
    newTag: latest
  - name: bingsu1103/promotion
    newTag: latest
  - name: bingsu1103/rating
    newTag: latest
  - name: bingsu1103/delivery
    newTag: latest
  - name: bingsu1103/sampledata
    newTag: latest
  - name: bingsu1103/recommendation
    newTag: latest
  - name: bingsu1103/customer
    newTag: latest
  - name: bingsu1103/location
    newTag: latest
  - name: bingsu1103/cart
    newTag: latest
  - name: bingsu1103/tax
    newTag: latest
  - name: bingsu1103/search
    newTag: latest
  - name: bingsu1103/webhook
    newTag: latest
  - name: bingsu1103/backoffice-bff
    newTag: latest
  - name: bingsu1103/storefront-bff
    newTag: latest
  - name: bingsu1103/payment-paypal
    newTag: latest
