apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
- ../../base
labels:
- includeSelectors: true
  pairs:
    environment: staging
patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
  target:
    kind: Deployment
    name: .*
images:
- name: bingsu1103/backoffice
  newTag: v1.0.1
- name: bingsu1103/backoffice-bff
  newTag: v1.0.1
- name: bingsu1103/cart
  newTag: v1.0.1
- name: bingsu1103/customer
  newTag: v1.0.1
- name: bingsu1103/inventory
  newTag: v1.0.1
- name: bingsu1103/media
  newTag: v1.0.1
- name: bingsu1103/order
  newTag: v1.0.1
- name: bingsu1103/payment
  newTag: v1.0.1
- name: bingsu1103/product
  newTag: v1.0.1
- name: bingsu1103/sampledata
  newTag: v1.0.1
- name: bingsu1103/search
  newTag: v1.0.1
- name: bingsu1103/storefront
  newTag: v1.0.1
- name: bingsu1103/storefront-bff
  newTag: v1.0.1
- name: bingsu1103/tax
  newTag: v1.0.1
