apiVersion: apps/v1
kind: Deployment
metadata:
  name: swagger-ui
  labels:
    app: swagger-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swagger-ui
  template:
    metadata:
      labels:
        app: swagger-ui
    spec:
      serviceAccountName: swagger-ui
      containers:
        - name: swagger-ui
          image: swaggerapi/swagger-ui:v4.16.0
          ports:
            - containerPort: 8080
          env:
            - name: BASE_URL
              value: /swagger-ui
            - name: URLS
              value: "[{ url: 'http://api.yas.local.com/product/v3/api-docs', name: 'Product' }, { url: 'http://api.yas.local.com/media/v3/api-docs', name: 'Media' }, { url: 'http://api.yas.local.com/customer/v3/api-docs', name: 'Customer' }, { url: 'http://api.yas.local.com/cart/v3/api-docs', name: 'Cart' }, { url: 'http://api.yas.local.com/order/v3/api-docs', name: 'Order' }, { url: 'http://api.yas.local.com/payment/v3/api-docs', name: 'Payment' }, { url: 'http://api.yas.local.com/inventory/v3/api-docs', name: 'Inventory' }, { url: 'http://api.yas.local.com/tax/v3/api-docs', name: 'Tax' }, { url: 'http://api.yas.local.com/search/v3/api-docs', name: 'Search' }]"
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"
