apiVersion: apps/v1
kind: Deployment
metadata:
  name: storefront-bff
spec:
  template:
    spec:
      containers:
        - name: storefront-bff
          env:
            - name: SPRING_DATA_REDIS_HOST
              value: "redis-master.dev.svc.cluster.local"
            - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI
              value: "http://identity.dev.svc.cluster.local/realms/Yas"
            - name: YAS_SERVICES_TOKEN_IDENTITY
              value: "http://identity.dev.svc.cluster.local/realms/Yas/protocol/openid-connect/token"
