apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-paypal
  labels:
    app: payment-paypal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-paypal
  template:
    metadata:
      labels:
        app: payment-paypal
    spec:
      serviceAccountName: payment-paypal
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: payment-paypal
          image: bingsu1103/payment-paypal:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8093
              protocol: TCP
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "k8s"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 60
            periodSeconds: 30
