apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-paypal
  labels:
    app: payment-paypal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-paypal
  template:
    metadata:
      labels:
        app: payment-paypal
    spec:
      serviceAccountName: payment-paypal      # BẮT BUỘC — TV4 dùng cho AuthorizationPolicy
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: payment-paypal
          image: bingsu1103/payment-paypal:latest
          ports:
            - containerPort: 8093
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "k8s"
            - name: SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE
              value: "3"
            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              value: "health,prometheus"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /payment-paypal/actuator/health
              port: 8093
            initialDelaySeconds: 60
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /payment-paypal/actuator/health
              port: 8093
            initialDelaySeconds: 180
            periodSeconds: 30
