apiVersion: v1
kind: Service
metadata:
  name: payment-paypal
  labels:
    app: payment-paypal
spec:
  selector:
    app: payment-paypal
  ports:
    - name: http
      port: 8093
      targetPort: http
      protocol: TCP
  type: ClusterIP
