apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels:
    app: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      serviceAccountName: payment      # BẮT BUỘC — TV4 dùng cho AuthorizationPolicy
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: payment
          image: bingsu1103/payment:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "k8s"
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              value: "http://identity:18080/realms/Yas"
            - name: SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE
              value: "3"
            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              value: "health,prometheus"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-postgresql:5432/payment?sslmode=disable"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "password"
            - name: YAS_SERVICES_ORDER
              value: "http://order:8085/order"
            - name: YAS_SERVICES_MEDIA
              value: "http://media:8083"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /payment/actuator/health
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /payment/actuator/health
              port: 8081
            initialDelaySeconds: 180
            periodSeconds: 30
