apiVersion: apps/v1
kind: Deployment
metadata:
  name: storefront-ui
  labels:
    app: storefront-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storefront-ui
  template:
    metadata:
      labels:
        app: storefront-ui
    spec:
      serviceAccountName: storefront-ui
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: storefront-ui
          image: bingsu1103/storefront:latest
          ports:
            - containerPort: 3000
          env:
            - name: API_BASE_PATH
              value: "http://storefront.yas.local.com/api"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "300m"
