apiVersion: v1
kind: Service
metadata:
  name: storefront-ui
  labels:
    app: storefront-ui
spec:
  selector:
    app: storefront-ui
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  type: ClusterIP
