apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: developer-build
resources:
  - ../../base
  - ../../base/location
  - dev-infra-destinationrules.yaml
labels:
  - pairs:
      environment: developer-build
    includeSelectors: false
patches:
  - path: patches/nodeport-patch.yaml
    target:
      kind: Service
      labelSelector: "app!=identity"
  - path: patches/identity-dev-externalname.yaml
    target:
      kind: Service
      name: identity
  - path: patches/static-storefront-bff-nodeport.yaml
    target:
      kind: Service
      name: storefront-bff
  - path: patches/virtualservice-hosts.yaml
    target:
      kind: VirtualService
      name: yas-ingress-vs
  - path: patches/rolling-update-one-node.yaml
    target:
      kind: Deployment
  - path: patches/use-dev-infra-media.yaml
    target:
      kind: Deployment
      name: media
  - path: patches/use-dev-infra-product.yaml
    target:
      kind: Deployment
      name: product
  - path: patches/use-dev-infra-order.yaml
    target:
      kind: Deployment
      name: order
  - path: patches/use-dev-infra-inventory.yaml
    target:
      kind: Deployment
      name: inventory
  - path: patches/use-dev-infra-payment.yaml
    target:
      kind: Deployment
      name: payment
  - path: patches/use-dev-infra-sampledata.yaml
    target:
      kind: Deployment
      name: sampledata
  - path: patches/use-dev-infra-customer.yaml
    target:
      kind: Deployment
      name: customer
  - path: patches/use-dev-infra-cart.yaml
    target:
      kind: Deployment
      name: cart
  - path: patches/use-dev-infra-tax.yaml
    target:
      kind: Deployment
      name: tax
  - path: patches/use-dev-infra-location.yaml
    target:
      kind: Deployment
      name: location
  - path: patches/use-dev-infra-search.yaml
    target:
      kind: Deployment
      name: search
  - path: patches/use-dev-infra-backoffice-bff.yaml
    target:
      kind: Deployment
      name: backoffice-bff
  - path: patches/use-dev-infra-storefront-bff.yaml
    target:
      kind: Deployment
      name: storefront-bff
  - path: patches/use-dev-infra-storefront-bff-config.yaml
    target:
      kind: ConfigMap
      name: storefront-bff-config
  - path: patches/storefront-ui.yaml
    target:
      kind: Deployment
      name: storefront-ui
images:
  - name: bingsu1103/media
    newTag: latest
  - name: bingsu1103/product
    newTag: latest
  - name: bingsu1103/order
    newTag: latest
  - name: bingsu1103/inventory
    newTag: latest
  - name: bingsu1103/payment
    newTag: latest
  - name: bingsu1103/promotion
    newTag: latest
  - name: bingsu1103/rating
    newTag: latest
  - name: bingsu1103/delivery
    newTag: latest
  - name: bingsu1103/sampledata
    newTag: latest
  - name: bingsu1103/recommendation
    newTag: latest
  - name: bingsu1103/customer
    newTag: latest
  - name: bingsu1103/location
    newTag: latest
  - name: bingsu1103/cart
    newTag: latest
  - name: bingsu1103/tax
    newTag: latest
  - name: bingsu1103/search
    newTag: latest
  - name: bingsu1103/webhook
    newTag: latest
  - name: bingsu1103/backoffice-bff
    newTag: latest
  - name: bingsu1103/storefront-bff
    newTag: latest
  - name: bingsu1103/storefront
    newTag: latest
  - name: bingsu1103/backoffice
    newTag: latest
