apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampledata
  labels:
    app: sampledata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sampledata
  template:
    metadata:
      labels:
        app: sampledata
    spec:
      serviceAccountName: sampledata      # BẮT BUỘC — TV4 dùng cho AuthorizationPolicy
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: sampledata
          image: bingsu1103/sampledata:latest
          ports:
            - containerPort: 8094
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "k8s"
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              value: "http://identity:18080/realms/Yas"
            - name: SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE
              value: "3"
            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              value: "health,prometheus"
            - name: SPRING_DATASOURCE_PRODUCT_URL
              value: "jdbc:postgresql://postgres-postgresql:5432/product"
            - name: SPRING_DATASOURCE_MEDIA_URL
              value: "jdbc:postgresql://postgres-postgresql:5432/media"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "password"
          resources:
            requests:
              memory: "512Mi"
              cpu: "100m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /sampledata/actuator/health
              port: 8094
            initialDelaySeconds: 60
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /sampledata/actuator/health
              port: 8094
            initialDelaySeconds: 180
            periodSeconds: 30
