apiVersion: v1
kind: Service
metadata:
  name: sampledata
  labels:
    app: sampledata
spec:
  selector:
    app: sampledata
  ports:
    - name: http
      port: 8094
      targetPort: http
      protocol: TCP
  type: ClusterIP
