apiVersion: apps/v1
kind: Deployment
metadata:
  name: rating
  labels:
    app: rating
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rating
  template:
    metadata:
      labels:
        app: rating
    spec:
      serviceAccountName: rating
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: rating
          image: bingsu1103/rating:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8089
              protocol: TCP
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "k8s"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 60
            periodSeconds: 30
