apiVersion: v1
kind: Service
metadata:
  name: rating
  labels:
    app: rating
spec:
  selector:
    app: rating
  ports:
    - name: http
      port: 8089
      targetPort: http
      protocol: TCP
  type: ClusterIP
