apiVersion: v1
kind: Service
metadata:
  name: rating
  labels:
    app: rating
spec:
  selector:
    app: rating
  ports:
    - port: 8089
      targetPort: 8089
      protocol: TCP
  type: ClusterIP
