apiVersion: apps/v1
kind: Deployment
metadata:
  name: backoffice-bff
  labels:
    app: backoffice-bff
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backoffice-bff
  template:
    metadata:
      labels:
        app: backoffice-bff
    spec:
      serviceAccountName: backoffice-bff      # BẮT BUỘC — TV4 dùng cho AuthorizationPolicy
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: backoffice-bff
          image: bingsu1103/backoffice-bff:latest
          ports:
            - containerPort: 8087
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "k8s"
            - name: SPRING_DATA_REDIS_HOST
              value: "redis-master"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8087
            initialDelaySeconds: 60
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8087
            initialDelaySeconds: 180
            periodSeconds: 30
