apiVersion: v1
kind: Service
metadata:
  name: backoffice-bff
  labels:
    app: backoffice-bff
spec:
  selector:
    app: backoffice-bff
  ports:
    - port: 8087
      targetPort: 8087
      protocol: TCP
  type: ClusterIP
