apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yas-developer-build
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/com-suon-bi-cha/gitops-manifest-k8s.git
    targetRevision: HEAD
    path: environments/developer-build
  destination:
    server: https://kubernetes.default.svc
    namespace: developer-build
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
