apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-connect
  labels:
    app: kafka-connect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-connect
  template:
    metadata:
      labels:
        app: kafka-connect
    spec:
      containers:
        - name: kafka-connect
          image: quay.io/debezium/connect:2.4
          ports:
            - containerPort: 8083
          env:
            - name: BOOTSTRAP_SERVERS
              value: "kafka:9092"
            - name: GROUP_ID
              value: "1"
            - name: CONFIG_STORAGE_TOPIC
              value: "my_connect_configs"
            - name: OFFSET_STORAGE_TOPIC
              value: "my_connect_offsets"
            - name: STATUS_STORAGE_TOPIC
              value: "my_connect_statuses"
            - name: KEY_CONVERTER
              value: "org.apache.kafka.connect.json.JsonConverter"
            - name: VALUE_CONVERTER
              value: "org.apache.kafka.connect.json.JsonConverter"
            - name: KEY_CONVERTER_SCHEMAS_ENABLE
              value: "false"
            - name: VALUE_CONVERTER_SCHEMAS_ENABLE
              value: "false"
          resources:
            requests:
              memory: "512Mi"
              cpu: "200m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
