apiVersion: apps/v1
kind: Deployment
metadata:
  name: search
  labels:
    app: search
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search
  template:
    metadata:
      labels:
        app: search
    spec:
      serviceAccountName: search      # BẮT BUỘC — TV4 dùng cho AuthorizationPolicy
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: search
          image: bingsu1103/search:latest
          ports:
            - containerPort: 8092
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "k8s"
            - name: ELASTICSEARCH_URL
              value: "elasticsearch:9200"
            - name: SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE
              value: "3"
            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              value: "health,prometheus"
            - name: YAS_SERVICES_PRODUCT
              value: "http://product:8080/product"
          resources:
            requests:
              memory: "512Mi"
              cpu: "100m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /search/actuator/health
              port: 8092
            initialDelaySeconds: 60
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /search/actuator/health
              port: 8092
            initialDelaySeconds: 180
            periodSeconds: 30
