apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - media/deployment.yaml
  - media/service.yaml
  - media/serviceaccount.yaml
  - product/deployment.yaml
  - product/service.yaml
  - product/serviceaccount.yaml
  - order/deployment.yaml
  - order/service.yaml
  - order/serviceaccount.yaml
  - inventory/deployment.yaml
  - inventory/service.yaml
  - inventory/serviceaccount.yaml
  - payment/deployment.yaml
  - payment/service.yaml
  - payment/serviceaccount.yaml
  - promotion/deployment.yaml
  - promotion/service.yaml
  - promotion/serviceaccount.yaml
  - rating/deployment.yaml
  - rating/service.yaml
  - rating/serviceaccount.yaml
  - delivery/deployment.yaml
  - delivery/service.yaml
  - delivery/serviceaccount.yaml
  - sampledata/deployment.yaml
  - sampledata/service.yaml
  - sampledata/serviceaccount.yaml
  - recommendation/deployment.yaml
  - recommendation/service.yaml
  - recommendation/serviceaccount.yaml
  - customer/deployment.yaml
  - customer/service.yaml
  - customer/serviceaccount.yaml
  - location/deployment.yaml
  - location/service.yaml
  - location/serviceaccount.yaml
  - cart/deployment.yaml
  - cart/service.yaml
  - cart/serviceaccount.yaml
  - tax/deployment.yaml
  - tax/service.yaml
  - tax/serviceaccount.yaml
  - search/deployment.yaml
  - search/service.yaml
  - search/serviceaccount.yaml
  - webhook/deployment.yaml
  - webhook/service.yaml
  - webhook/serviceaccount.yaml
  - backoffice-bff/deployment.yaml
  - backoffice-bff/service.yaml
  - backoffice-bff/serviceaccount.yaml
  - storefront-bff/deployment.yaml
  - storefront-bff/service.yaml
  - storefront-bff/serviceaccount.yaml
  - payment-paypal/deployment.yaml
  - payment-paypal/service.yaml
  - payment-paypal/serviceaccount.yaml
