apiVersion: apps/v1
kind: Deployment
metadata:
  name: promotion
  labels:
    app: promotion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: promotion
  template:
    metadata:
      labels:
        app: promotion
    spec:
      serviceAccountName: promotion      # BẮT BUỘC — TV4 dùng cho AuthorizationPolicy
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: promotion
          image: bingsu1103/promotion:latest
          ports:
            - containerPort: 8092
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "k8s"
            - name: SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE
              value: "3"
            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              value: "health,prometheus"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-postgresql:5432/promotion"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "password"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /promotion/actuator/health
              port: 8092
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /promotion/actuator/health
              port: 8092
            initialDelaySeconds: 120
            periodSeconds: 30
