apiVersion: v1
kind: Service
metadata:
  name: promotion
  labels:
    app: promotion
spec:
  selector:
    app: promotion
  ports:
    - port: 8092
      targetPort: 8092
      protocol: TCP
  type: ClusterIP
