apiVersion: v1
kind: Service
metadata:
  name: promotion
  labels:
    app: promotion
spec:
  selector:
    app: promotion
  ports:
    - name: http
      port: 8092
      targetPort: http
      protocol: TCP
  type: ClusterIP
