apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
- ../../base
labels:
- includeSelectors: false
  includeTemplates: true
  pairs:
    environment: dev
images:
  - name: bingsu1103/media
    newTag: latest
  - name: bingsu1103/product
    newTag: latest
  - name: bingsu1103/order
    newTag: latest
  - name: bingsu1103/inventory
    newTag: latest
  - name: bingsu1103/payment
    newTag: latest
  - name: bingsu1103/sampledata
    newTag: latest
  - name: bingsu1103/customer
    newTag: latest
  - name: bingsu1103/cart
    newTag: latest
  - name: bingsu1103/tax
    newTag: latest
  - name: bingsu1103/search
    newTag: latest
  - name: bingsu1103/backoffice-bff
    newTag: latest
  - name: bingsu1103/storefront-bff
    newTag: latest
  - name: bingsu1103/storefront
    newTag: latest
  - name: bingsu1103/backoffice
    newTag: latest
