apiVersion: apps/v1
kind: Deployment
metadata:
  name: storefront-bff
  labels:
    app: storefront-bff
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storefront-bff
  template:
    metadata:
      labels:
        app: storefront-bff
    spec:
      serviceAccountName: storefront-bff      # BẮT BUỘC — TV4 dùng cho AuthorizationPolicy
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: storefront-bff
          image: bingsu1103/storefront-bff:latest
          ports:
            - containerPort: 8087
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "k8s"
            - name: SPRING_CONFIG_ADDITIONAL_LOCATION
              value: "optional:file:/config/"
            - name: SPRING_DATA_REDIS_HOST
              value: "redis-master"
          volumeMounts:
            - name: storefront-bff-config
              mountPath: /config/application-k8s.yaml
              subPath: application-k8s.yaml
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8087
            initialDelaySeconds: 60
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8087
            initialDelaySeconds: 180
            periodSeconds: 30
      volumes:
        - name: storefront-bff-config
          configMap:
            name: storefront-bff-config
