apiVersion: v1
kind: Service
metadata:
  name: storefront-bff
  labels:
    app: storefront-bff
spec:
  selector:
    app: storefront-bff
  ports:
    - name: http
      port: 8087
      targetPort: http
      protocol: TCP
  type: ClusterIP
